inspec/inspec-gcp

- docs/resources/google_compute_address.md.erb
- docs/resources/google_compute_firewall.md.erb
- docs/resources/google_compute_image.md.erb
- docs/resources/google_compute_instance.md.erb
- docs/resources/google_compute_instance_group.md.erb
- docs/resources/google_compute_instances.md.erb
- docs/resources/google_container_cluster.md.erb
- docs/resources/google_container_node_pool.md.erb
- docs/resources/google_project.md.erb
- docs/resources/google_project_iam_custom_role.md.erb
- docs/resources/google_service_account.md.erb
- docs/resources/google_storage_bucket.md.erb
- libraries/google_compute_image.rb
- libraries/google_compute_instances.rb
- test/integration/verify/controls/generic_iam_role.rb
- test/integration/verify/controls/generic_storage_bucket.rb
- test/integration/verify/controls/google_compute_vms.rb
- test/integration/verify/controls/google_compute_vms_loop.rb
Also minor corrections to a couple of resources.
Used InSpec FilterTable to create first plural resource for compute instances, including exammple controls and documentation.
> Added missing documentation following InSpec standards, resolves #11.

- libraries/google_compute_firewall.rb
- libraries/google_compute_image.rb
- libraries/google_compute_instance_group.rb
- libraries/google_container_node_pool.rb
- libraries/google_service_account.rb
* Ensure resources have consistent exists methods.
* Corrected a coupld of arguments in example doc strings.
> Fixes according to issues: #19, #20, #21 and #22.

- Gemfile
- docs/resources/google_compute_firewalls.md.erb
- docs/resources/google_compute_instance.md.erb
- docs/resources/google_compute_instances.md.erb
- docs/resources/google_compute_zone.md.erb
- docs/resources/google_compute_zones.md.erb
- libraries/google_compute_firewall.rb
- libraries/google_compute_firewalls.rb
- libraries/google_compute_instance.rb
- libraries/google_compute_instances.rb
- libraries/google_compute_zone.rb
- libraries/google_compute_zones.rb
- test/integration/configuration/gcp_inspec_config.rb
- test/integration/verify/controls/generic_external_vm.rb
- test/integration/verify/controls/generic_external_vm_data_disk.rb
- test/integration/verify/controls/google_compute_firewalls.rb
- test/integration/verify/controls/google_compute_firewalls_loop.rb
- test/integration/verify/controls/google_compute_instance_label_loop.rb
- test/integration/verify/controls/google_compute_vms.rb
- test/integration/verify/controls/google_compute_zones.rb
- test/integration/verify/controls/google_compute_zones_loop.rb
- test/integration/verify/inspec.yml
Includes resources required for upcoming blog post.
> Add plural resources

- test/integration/build/gcp.tf
- test/integration/verify/controls/google_compute_vms.rb
> Resolve Debian 8 EOL issue, now pin all tf module versions explicitly.

- CHANGELOG.md
- inspec.yml
- test/integration/verify/inspec.yml
> Bump version to v0.5.0

- README.md
- docs/resources/google_compute_region.md
- docs/resources/google_compute_regions.md
- libraries/google_compute_region.rb
- libraries/google_compute_regions.rb
- test/integration/configuration/gcp_inspec_config.rb
- test/integration/verify/controls/google_compute_region.rb
- test/integration/verify/controls/google_compute_region_zones_loop.rb
- test/integration/verify/controls/google_compute_regions.rb
- test/integration/verify/controls/google_compute_regions_loop.rb
> Add google_compute_region(s) resources, tests etc. and updated README.

- docs/resources/google_logging_project_sinks.md
- docs/resources/google_project_logging_audit_config.md
- docs/resources/google_project_metric.md
- docs/resources/google_project_metrics.md
- libraries/google_logging_project_sinks.rb
- libraries/google_project_logging_audit_config.rb
- libraries/google_project_metric.rb
- libraries/google_project_metrics.rb
- libraries/google_storage_bucket.rb
- test/integration/verify/controls/google_logging_project_sinks.rb
- test/integration/verify/controls/google_project_logging_audit_config.rb
More details below:
- Added google_project_metric(s)
- Added google_project_logging_audit_config resource
- Added google_logging_project_sinks resource and helper method to storage buckets for versioning.
> Project audit logging

- docs/resources/google_compute_project_info.md
- libraries/google_compute_instance.rb
- libraries/google_compute_project_info.rb
- test/integration/verify/controls/google_compute_project_info.rb
More details:
- Added google_compute_project_info resource
- Added helpers to VM instance resource
> VM Updates

- docs/resources/google_compute_zones.md
- docs/resources/google_sql_database_instance.md
- docs/resources/google_sql_database_instances.md
- docs/resources/google_sql_users.md
- libraries/google_sql_database_instance.rb
- libraries/google_sql_database_instances.rb
- libraries/google_sql_users.rb
- test/integration/build/gcp.tf
- test/integration/configuration/gcp_inspec_config.rb
- test/integration/verify/controls/google_sql_database_instance.rb
- test/integration/verify/controls/google_sql_database_instances.rb
- test/integration/verify/controls/google_sql_users.rb
More details:
- Added Cloud SQL resources - google_sql_database_instance(s), google_sql_users
- Docs, tests for the above
- Minor fix to zones doc
> Cloud SQL resources

- docs/resources/google_storage_bucket_objects.md
- libraries/google_storage_bucket.rb
- libraries/google_storage_bucket_objects.rb
- libraries/google_storage_default_object_acl.rb
- libraries/google_storage_object_acl.rb
- test/integration/verify/controls/google_storage_bucket_objects.rb
More details:
- Added google_storage_bucket_objects resource
- Reworked google_storage_bucket_acl and google_storage_default_object_acl to better cope with Not Found exceptions
- Helper method for logging in google_storage_bucket
> Storage updates

- test/integration/configuration/gcp_inspec_config.rb
- test/integration/verify/controls/google_storage_bucket_acl.rb
- test/integration/verify/controls/google_storage_bucket_iam_binding.rb
- test/integration/verify/controls/google_storage_default_object_acl.rb
- test/integration/verify/controls/google_storage_object_acl.rb
> Updates to controls affected by service account name change.

- docs/resources/google_project_alert_policies.md
- docs/resources/google_project_alert_policy.md
- docs/resources/google_project_alert_policy_condition.md
- docs/resources/google_project_metrics.md
- docs/resources/google_user.md
- docs/resources/google_users.md
- libraries/google_compute_instance.rb
- libraries/google_compute_network.rb
- libraries/google_container_cluster.rb
- libraries/google_project_alert_policies.rb
- libraries/google_project_alert_policy.rb
- libraries/google_project_alert_policy_condition.rb
- libraries/google_project_metric.rb
- libraries/google_project_metrics.rb
- libraries/google_user.rb
- libraries/google_users.rb
Merge is pending InSpec release for https://github.com/inspec/train/pull/349 and https://github.com/inspec/train/pull/348
Summary:
- Adding google_user(s) resources based on the new train admin_client.
- Added resources corresponding to project alert policies
- Added helper method to container cluster
- Added metric_type attribute to project metrics plural resource
> Adding google_user(s) and project alert policy resources

- libraries/google_project.rb
The google_project resource documentation indicates that resources are
instantiated with :project, but the google_project was storing the value
of :name for use with `#to_s`. This inconsistency leads to InSpec output
like the following:
✔  Project  should exist
✔  Project  name should eq "dev-host"
✔  Project  parent.type should eq "folder"
✔  Project  parent.id should eq "743996818495"
This commit adds :project as a fallback value for `@display_name,`
ensuring that google_projects will format correctly in the InSpec
report.
> Improve google_project#to_s output

- libraries/google_compute_region.rb
When running the cis-gcp-benchmark-level2 profile against my gcp project, I noticed errors like this for a few controls:
I made two changes to the PR, one to replace `false` with `[]`. Otherwise controls like these:
```
google_compute_region(project: gcp_project_id, name: region_name).zone_names.each do |zone_name|
```
will raise an error as well since they expect zone_names to be array and not boolean.
Second change is on the nil checking of `@region.zones`. It was not returning `[]`, here's my pry play:
```
[1] pry(#<#<Class:0x00007f9d7f9b7bb0>>)> @region.zones
=> nil
[2] pry(#<#<Class:0x00007f9d7f9b7bb0>>)> defined?(@region.zones)
=> "method"
[3] pry(#<#<Class:0x00007f9d7f9b7bb0>>)> puts "bingo" if !defined?(@region.zones)
=> nil
[4] pry(#<#<Class:0x00007f9d7f9b7bb0>>)> myvar=nil
=> …
```
> Fix nil exception when no zones are returned for a region

- libraries/google_project_logging_audit_config.rb
Similar to https://github.com/inspec/inspec-gcp/pull/67
```
$ bundle exec inspec exec ~/git/summit-demo -t gcp:// --attrs ~/git/summit-demo/attrs.yaml
bundler: failed to load command: inspec (/usr/local/lib/ruby/gems/2.4.0/bin/inspec)
NoMethodError: undefined method `each' for nil:NilClass
libraries/google_project_logging_audit_config.rb:25:in `block in initialize'
libraries/gcp_backend.rb:28:in `catch_gcp_errors'
libraries/google_project_logging_audit_config.rb:20:in `initialize'
/Users/apop/git/inspec/lib/inspec/plugin/v1/plugin_types/resource.rb:68:in `initialize'
/Users/apop/git/inspec/lib/inspec/resource.rb:51:in `new'
/Users/apop/git/inspec/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
```
> Fix nil checks in google_project_logging_audit_config resource

- libraries/google_compute_firewall.rb
- libraries/google_compute_instance.rb
- libraries/google_compute_instance_group.rb
- libraries/google_compute_network.rb
- libraries/google_compute_project_info.rb
- libraries/google_compute_region.rb
- libraries/google_compute_subnetwork.rb
- libraries/google_compute_zone.rb
- libraries/google_container_node_pool.rb
- libraries/google_dns_managed_zone.rb
- libraries/google_kms_crypto_key.rb
- libraries/google_kms_key_ring.rb
- libraries/google_project.rb
- libraries/google_project_alert_policies.rb
- libraries/google_project_alert_policy.rb
- libraries/google_project_alert_policy_condition.rb
- libraries/google_project_logging_audit_config.rb
- libraries/google_sql_database_instance.rb
- libraries/google_storage_bucket.rb
- libraries/google_storage_bucket_object.rb
- libraries/google_user.rb
Follow up after updating two resources here:
https://github.com/inspec/inspec-gcp/pull/67
https://github.com/inspec/inspec-gcp/pull/68
this PR goes over all resources to complement `defined?` with `nil?` checks
This is why:
```
[3] pry(#<#<Class:0x00007ffe9162b028>>)> @region.zones
=> ["https://www.googleapis.com/compute/v1/projects/alex-pop-project/zones/asia-east1-a",
"https://www.googleapis.com/compute/v1/projects/alex-pop-project/zones/asia-east1-b",
"https://www.googleapis.com/compute/v1/projects/alex-pop-project/zones/asia-east1-c"]
[4] pry(#<#<Class:0x00007ffe9162b028>>)> puts "bingo" if !defined?(@region.zones)
=> nil
[5] pry(#<#<Class:0x00007ffe9162b028>>)> exit
[1] pry(#<#<Class:0x00007ffe9162b028>>)> @region.zones
=> nil
[2] pry(#<#<Class:0x00007ffe9162b028>>)> puts "bingo" if …
```
> Extra nil checks, some error values changed

- libraries/google_storage_bucket_acl.rb
- test/integration/verify/controls/google_storage_bucket_acl.rb
Obvious fix.
Closes https://github.com/inspec/inspec-gcp/issues/80.
> Fix an error when the bucket ACL doesn't exist

- libraries/google_dns_managed_zone.rb
An API change seemingly occurred where expected DNSSEC default key specs no longer existed e.g. 
"keySigning" became "KEY_SIGNING"
"zoneSigning" became "ZONE_SIGNING"
This PR updates to the new values.
> Update the DNS key and zone signing methods to the new key names.

- docs/resources/google_compute_region_instance_group_manager.md
- docs/resources/google_compute_region_instance_group_managers.md
- libraries/google_compute_region_instance_group_manager.rb
- libraries/google_compute_region_instance_group_managers.rb
- test/integration/build/gcp.tf
- test/integration/verify/controls/google_compute_region_instance_group_managers.rb
This PR allow users to perform validation of regional instance groups
I updated integrations tests to create a regional instance group base on a dummy instance template. I set to 0 target size, instances are not needed for this test.
> Added support for google_compute_region_instance_group_manager

- README.md
- docs/resources/google_project_alert_policies.md
- docs/resources/google_project_alert_policy.md
- inspec.yml
- test/integration/verify/inspec.yml
> Update README for new resources

- docs/resources/google_compute_forwarding_rule.md
- docs/resources/google_compute_forwarding_rules.md
- libraries/google_compute_forwarding_rule.rb
- libraries/google_compute_forwarding_rules.rb
- test/integration/configuration/gcp_inspec_config.rb
- test/integration/verify/controls/google_compute_forwarding_rule.rb
- test/integration/verify/controls/google_compute_forwarding_rules.rb
Hello,
Please find 2 resources to : 
- List all forwarding rules
- Get details for a specific forwarding rule
I used the existing google LB to perform validation tests.
Jérôme.
> Add support for google_compute_forwarding_rules and google_compute_forwarding_rule

- README.md
- libraries/google_compute_forwarding_rules.rb
> Fix for forwarding rules with nil network and update README.

- docs/resources/google_projects.md
- libraries/google_projects.rb
> Implement ability to filter GCP projects by lifecycle state

- docs/resources/google_organization.md
- docs/resources/google_organizations.md
- libraries/google_organization.rb
- libraries/google_organizations.rb
- test/integration/verify/controls/google_organization.rb
- test/integration/verify/controls/google_organizations.rb
I wasn't really sure how I should have gone about testing this as you need to have a G Suite account for this (and I did not want to use the company one), but I promise everything works. I have a screenshot for it! 😛
> Add ability to test individual as well as multiple organisations

- README.md
I wanted to run the tests so I ran through the instructions in the README. There were a couple of missing steps (enabling billing and services) and some ambiguous or confusing bits.
This fixes all of those! The location/region stuff should be re-added if #114 is fixed.
> improve test info in README

- libraries/google_compute_address.rb
This adds an `exists?` method to `google_compute_address`. The documentation for `google_compute_address` shows:
```
describe google_compute_address(project: 'chef-inspec-gcp', location: 'us-west2', name: 'gcp-inspec-test') do
it { should exist }
end
```
but that will fail because there is no `exists?` method. This PR fixes that. 
I'm not sure if this is affected by the magic modules I see in the codebase. Also unsure if y'all would prefer if we fix the documentation since there's already an `address_ip_exists` method.
Let me know if this is the right approach and I can also look into adding tests!
> Add exists? method to google_compute_address

- test/integration/build/gcp.tf
- test/integration/verify/controls/google_compute_regional_disk.rb
> Fix for regional compute disk creation and testing.

- README.md
`https://github.com/inspec/inspec-gcp/blob/master/README.md` page has a broken link
FIx the HTML link
> docs: typo/fix broken URL link

- libraries/google_dns_managed_zones.rb
Updated version of rubocop apparently cares about this
Update to casecmp for new version of rubocop
> Rubocop update

- libraries/google_compute_instance.rb
If a `google_compute_instance` has no service account scopes assigned, the following logic:
```
describe "[#{gcp_project_id}] Instance #{instance[:zone]}/#{instance[:name]}" do
subject { google_compute_instance(project: gcp_project_id, zone: instance[:zone], name: instance[:name]) }
its('service_account_scopes') { should_not include 'https://www.googleapis.com/auth/cloud-platform' }
end
```
causes:
```
×  [my-project] Instance us-central1-f/my-instance service_account_scopes 
undefined method `[]' for nil:NilClass
```
This adds a quick check to see if that dynamic method is available before seeing what's in the array.
N/A
> service_account_scopes nilclass

- docs/resources/google_iam_service_account.md
Using example results in - 
```[2020-09-10T10:40:32-04:00] ERROR: Failed to load profile inspec-dc-gcp: Failed to load source for controls/iam.rb: undefined method `google_iam_service_account' for #<Inspec::ControlEvalContext:0x00007ffd7fb2b130>
Profile:         GCP InSpec Profile (inspec-dc-gcp)
Version:         0.1.0
Failure Message: Failed to load source for controls/iam.rb: undefined method `google_iam_service_account' for #<Inspec::ControlEvalContext:0x00007ffd7fb2b130>```
submitting.
Please ensure commits have been …
> Adjusting examples to use updated lib name

- Gemfile
Gets the Ruby 2.5 tests to pass again, using Bundler.
> Conditionally pin chef-utils on ruby 2.5

- libraries/gcp_backend.rb
`@connection` is only set if `opts[:use_http_transport]` is set, however if that is the case then calling `resource_id` raises an error. This adds safe navigation to connection in order to avoid this error.
This is an error I started encountering when testing changes related to https://github.com/googleapis/google-auth-library-ruby/issues/354.
> Do not raise an error when calling resource_id if @connection is nil

- generate/libraries/gcp_backend.rb
- libraries/gcp_backend.rb
The GoogleAuth library supports creating credentials for multiple credential types. The current state of inspec-gcp limits users passing a `GOOGLE_APPLICATION_CREDENTIALS` file to only be able to use service accounts.
This allows users utilizing authentication types other than service accounts to pass an appropriate `GOOGLE_APPLICATION_CREDENTIALS` file. It is no longer recommended by Google to utilize a service account directly and Workload Identity Federation is the recommended replacement. I am trying to implement Workload Identity Federation in googleauth and utilize it with InSpec and this is one of the issues I encountered.
This is relevant to the work I am doing in https://github.com/googleapis/google-auth-library-ruby/issues/354
> Allow more flexibility to GOOGLE_APPLICATION_CREDENTIALS parsing

- libraries/google_sql_database_instance.rb
Signed-off-by: Soumyodeep Karmakar <soumyo.k13@gmail.com>
We got this bellow offense in the buildkite. We are fixing the mentioned offense.
Offenses:
libraries/google_sql_database_instance.rb:104:33: C: [Correctable] Style/ZeroLengthPredicate: Use empty? instead of size.zero?.
return '' if !@ip_addresses.size.zero? || @ip_addresses[0].ip_address.nil?
^^^^^^^^^^
971 files inspected, 1 offense detected, 1 offense autocorrectable
RuboCop failed!
🚨 Error: The command exited with status 1
user command error: The plugin docker command hook exited with status 1
> RESOURCE-586  Fix the build lint issue in inspec-gcp

- libraries/google/container/property/nodepool_config.rb
submitting.
FIx for wrong attribute provided.
older config - workloadMetaConfig changed to workloadMetadataConfig
> CHEF-4288 wrong atrribute workloadMetadataConfig fixed

- Gemfile
Recent version pinning is breaking the pipeline causing the timeout error.
Since it is blocking, we are reverting the version pinning changes 
> Reverted version pinning

- docs/resources/google_service_account_key.md
- docs/resources/google_service_account_keys.md
- libraries/google_service_account_key.rb
- libraries/google_service_account_keys.rb
Add missing properties to google_service_account_key resource as per latest response received from the API.
CHEF-7374: [GCP InSpec Resource] IAM - Project Service Account keys
> CHEF-7374: Add missing properties to google_service_account_key resource

- Gemfile
Verify pipeline was failing due to timeout issues.
Removed unused gem and added latest inspec-core-bin gem
> Fix Verify Pipeline timeout issue

- .expeditor/verify.pipeline.yml
The current Docker image version (ruby:3.1) encounters a ThreadError due to restrictions imposed by libseccomp, blocking certain system calls necessary for the operation of Ruby's open3 module.
```
/usr/local/lib/ruby/3.1.0/open3.rb:223:in `detach': can't create Thread: Operation not permitted (ThreadError)
```
This PR addresses the issue encountered in the current Docker image setup by updating the Docker image version from ruby:3.1 to ruby:3.1-bullseye.
_Note: This is a workaround_
CHEF-11234: CI is breaking for inspec, inspec-gcp, and train due to issue with docker image used for the tests
https://github.com/docker-library/python/issues/837#issuecomment-1599640563
https://github.com/docker-library/redmine/discussions/307#discussioncomment-7711691
> CHEF-11234: Fix broken CI issue `can't create Thread: Operation not permitted (ThreadError)`

- Gemfile
parser 3.3.1.0 introduced https://github.com/whitequark/parser/pull/1000, which causes this failure:
```
% 
bundle exec inspec check /workdir --chef-license=accept-silent
    bundler: failed to load command: inspec (/usr/local/bundle/bin/inspec)
    /usr/local/bundle/gems/inspec-core-5.22.40/lib/inspec/utils/profile_ast_helpers.rb:7:in `<class:CollectorBase>': 
uninitialized constant Parser::AST::Processor::Mixin (NameError)
```
Fix this by requiring the right version of the `parser` gem.
Closes #[7029](https://github.com/inspec/inspec/issues/7029)
> Fix uninitialized constant Parser::AST::Processor::Mixin

- libraries/google/orgpolicy/property/policy_alternate.rb
- libraries/google/orgpolicy/property/policy_alternate_spec.rb
- libraries/google/orgpolicy/property/policy_alternate_spec_rules.rb
- libraries/google/orgpolicy/property/policy_alternate_spec_rules_condition.rb
- libraries/google/orgpolicy/property/policy_alternate_spec_rules_values.rb
- libraries/google/orgpolicy/property/policy_dry_run_spec.rb
- libraries/google/orgpolicy/property/policy_dry_run_spec_rules.rb
- libraries/google/orgpolicy/property/policy_dry_run_spec_rules_condition.rb
- libraries/google/orgpolicy/property/policy_dry_run_spec_rules_values.rb
- libraries/google/orgpolicy/property/policy_spec.rb
- libraries/google/orgpolicy/property/policy_spec_rules.rb
- libraries/google/orgpolicy/property/policy_spec_rules_condition.rb
- libraries/google/orgpolicy/property/policy_spec_rules_values.rb
- libraries/google_orgpolicy_organization_policies.rb
- libraries/google_orgpolicy_organization_policy.rb
Renaming orgpolicy properties to reuse the same properties for other org policy resources
> Rename orgpolicy properties
