README.md
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> update readme with api and quota settings

inspec.yml, test/integration/verify/inspec.yml
=> Added minimum supported inspec version to inspec.yml

README.md
=> add kudos for @martezr

inspec.yml, test/integration/verify/inspec.yml
=> Bump version to 0.4.0

docs/resources/google_compute_subnetworks.md, docs/resources/google_dns_managed_zone.md, docs/resources/google_dns_managed_zones.md, libraries/google_compute_firewall.rb, libraries/google_compute_network.rb, libraries/google_compute_subnetworks.rb, libraries/google_dns_managed_zone.rb, libraries/google_dns_managed_zones.rb
More details:
- Added google_dns_managed_zone(s)
- Added property to subnetworks resource
- New helper methods in firewall and network resources
=> Networking related updates

Dockerfile
- Updated to have multiple layers
- Added cleanup layer
- Updated to 0.11.8 version of TF
Signed-off-by: JJ Asghar <jj@chef.io>
=> Updated Dockerfile with more layers and terraform

docs/resources/google_compute_instance.md, docs/resources/google_project.md, libraries/google_compute_instance.rb, libraries/google_project.rb
The changes allow to perform validation based on content of particular metadata and label elements. Very useful for organizations that impose standards on those type of things.
=> Added support for metadata and label content based compliance

CHANGELOG.md, README.md, docs/resources/google_compute_instance.md, inspec.yml, test/integration/verify/inspec.yml
Updates to README and other docs.
=> Bump version to v0.6.0

CHANGELOG.md, inspec.yml, test/integration/verify/inspec.yml
=> Version bump v0.7.0.

.rubocop.yml, libraries/google_compute_firewall.rb
=> Improve fw resources to handle 'all' cases.

CHANGELOG.md, README.md
=> Updating README with new resources and adding CHANGELOG for v0.8.0.

README.md, test/integration/build/gcp-mm.tf, test/integration/configuration/mm-attributes.yml
Update integration test and available resources documentation.  Change MM container cluster region to default to gcp_location. Fixes #114.
=> Ensure region selection works as expected.

test/integration/verify/controls/google_container_regional_cluster.rb
=> Update google_container_regional_cluster control to use correct region.

test/integration/verify/controls/google_container_regional_clusters.rb
=> Update for google_container_regional_clusters control.

libraries/google_container_cluster.rb
Should fix https://github.com/inspec/inspec-gcp/issues/136
=> Logging enabled regex

CHANGELOG.md, inspec.yml, test/integration/verify/inspec.yml
=> Version bump v0.11.0

docs/resources/google_organization_policy.md, libraries/google_organization_policy.rb
Signed-off-by: Sam Levenick <slevenick@google.com>
Fix docs in `google_organization_policy`, add examples
No functional changes
=> Fix docs for organization policy

Gemfile, Rakefile, test/integration/configuration/gcp_inspec_config.rb
=> Remove passgen dependency.

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.MD, CONTRIBUTING.md, ISSUE_TEMPLATE.md, README.md
Updating state as per OSS policy.  Also update issue, contributing, PR templates etc. as per other cloud resource packs.
=> OSS and templates update

test/integration/configuration/gcp_inspec_config.rb
=> Ensure an agreeable default value for gcp_organization_id for skipping affected tests.

test/integration/build/gcp-mm.tf
=> Propagate default empty string for org id.

.rubocop.yml
=> Update rubocop deprecated settings.

.expeditor/config.yml, .rubocop.yml
=> Update expeditor configuration to allow bumping major version.

libraries/google_kms_crypto_key.rb
Signed-off-by: Jon Cowie <jonlives@gmail.com>
Fixes issue #366 to add error handling when primary state attribute is missing
=> Fix for #366 to add error handling for missing primary_state attribute

libraries/google_project_iam_binding.rb
Signed-off-by: sa-progress <samir.anand@progress.com>
submitting.
=> google_project_iam_binding.rb file added

README.md
Link to "InSpec GCP Deep Dive" blog post is currently broken.
N/A
=> Fix blog post link

.rubocop.yml, build/inspec/Gemfile, build/inspec/test/integration/verify/controls/google_data_loss_prevention_stored_info_type.rb, build/inspec/test/integration/verify/controls/google_data_loss_prevention_stored_info_types.rb
=> Naming linting fix

.expeditor/verify.pipeline.yml
=> Removed the support for expeditor changes for ruby run time 2.7

Gemfile
=> Update inspec version pinning in Gemfile
